var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/client/apple-interiors-kokapet/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1rv50kf._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0wpi585.js")
R.c("server/chunks/ssr/[root-of-the-server]__12_m7g-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1374eg-._.js")
R.c("server/chunks/ssr/app_layout_jsx_181co3-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_1epi4n8._.js")
R.c("server/chunks/ssr/app_client_apple-interiors-kokapet_layout_jsx_1ioqtzh._.js")
R.c("server/chunks/ssr/_next-internal_server_app_client_apple-interiors-kokapet_page_actions_1k9mndt.js")
R.m(374927)
module.exports=R.m(374927).exports
