var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/client/sahani-interiors-banjara-hills/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1drj4i_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1dc6gwu.js")
R.c("server/chunks/ssr/[root-of-the-server]__12_m7g-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1374eg-._.js")
R.c("server/chunks/ssr/app_layout_jsx_181co3-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_1epi4n8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1-dsf--._.js")
R.c("server/chunks/ssr/1oeh_server_app_client_sahani-interiors-banjara-hills_page_actions_1br7w3k.js")
R.m(173403)
module.exports=R.m(173403).exports
