var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/client/little-elly-preschool-tolichowki/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0vy5z7v._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1vfj7b4.js")
R.c("server/chunks/ssr/[root-of-the-server]__12_m7g-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1374eg-._.js")
R.c("server/chunks/ssr/app_layout_jsx_181co3-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_1epi4n8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0_kx_h8._.js")
R.c("server/chunks/ssr/1oeh_server_app_client_little-elly-preschool-tolichowki_page_actions_1eoy9m8.js")
R.m(1509)
module.exports=R.m(1509).exports
