var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/client/maximum-tax-consultant/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1pp89eg._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1csnksw.js")
R.c("server/chunks/ssr/[root-of-the-server]__12_m7g-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1374eg-._.js")
R.c("server/chunks/ssr/app_layout_jsx_181co3-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_1epi4n8._.js")
R.c("server/chunks/ssr/app_client_maximum-tax-consultant_layout_jsx_1mq--po._.js")
R.c("server/chunks/ssr/_next-internal_server_app_client_maximum-tax-consultant_page_actions_15whrv5.js")
R.m(28371)
module.exports=R.m(28371).exports
