var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/client/eurokids-preschool-rajendranagar/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0byc7gd._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0qz-7i8.js")
R.c("server/chunks/ssr/[root-of-the-server]__12_m7g-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1374eg-._.js")
R.c("server/chunks/ssr/app_layout_jsx_181co3-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_1epi4n8._.js")
R.c("server/chunks/ssr/app_client_eurokids-preschool-rajendranagar_layout_jsx_0_u5neq._.js")
R.c("server/chunks/ssr/1oeh_server_app_client_eurokids-preschool-rajendranagar_page_actions_01c7kyj.js")
R.m(796665)
module.exports=R.m(796665).exports
