var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/client/aqua-shine-detailing-attapur/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0lyo6sl._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1c6ec27.js")
R.c("server/chunks/ssr/[root-of-the-server]__12_m7g-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1374eg-._.js")
R.c("server/chunks/ssr/app_layout_jsx_181co3-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_1epi4n8._.js")
R.c("server/chunks/ssr/app_client_aqua-shine-detailing-attapur_layout_jsx_10ohasc._.js")
R.c("server/chunks/ssr/1oeh_server_app_client_aqua-shine-detailing-attapur_page_actions_1ad62s7.js")
R.m(314291)
module.exports=R.m(314291).exports
